from typing import Tuple, List, Optional
import numpy as np
from .base import PhantomGenerator


class Octahedron(PhantomGenerator):
    """
    A clean regular octahedron centered in the voxel grid.

    * Code generated by Grok.
    """
    def generate(
        self,
        size: int = 256,
        scale: float = 0.7,  # Controls the relative size of the octahedron (0 to 1)
    ):
        """Generate a solid regular octahedron voxel.

        The octahedron is defined using the L1 norm: |x| + |y| + |z| <= r

        Args:
            size: the size of the voxel.
            scale: relative scale factor controlling the octahedron size.
                   1.0 roughly touches the faces of the bounding box.

        Returns:
            shape=(size, size, size), dtype=uint8, 0 or 1
        """
        voxel = self.get_blank_voxel(size)
        center = size // 2

        # Generate coordinate arrays
        z, y, x = np.ogrid[:size, :size, :size]

        # Normalize coordinates to approximately [-1, 1] range
        X = (x - center) / (size * 0.5)
        Y = (y - center) / (size * 0.5)
        Z = (z - center) / (size * 0.5)

        # Regular octahedron defined by Manhattan distance (L1 norm)
        # Adjust radius so that scale=1 gives a visually full-sized octahedron
        radius = scale * np.sqrt(2)

        octa_mask = np.abs(X) + np.abs(Y) + np.abs(Z) <= radius

        voxel[octa_mask] = 1

        return voxel