from typing import Tuple, List, Optional
import numpy as np
from .base import PhantomGenerator


class Tetrahedron(PhantomGenerator):
    """
    A tetrahedron (triangular pyramid) with bubbles inside.

    * Code generated by Qwen-Coder.
    """

    def generate(
            self, size: int = 256, height: int = 100,
    ):
        """ Generate a tetrahedron with bubbles inside.

        Args:
            size: the size of the voxel.
            height: the height of the tetrahedron.

        Returns:
            shape=(size, size, size), dtype=uint8, 0 or 1
        """
        voxel = self.get_blank_voxel(size)

        z, y, x = np.ogrid[:size, :size, :size]
        center = size // 2

        # Define the 4 vertices of a regular tetrahedron centered at (center, center, center)
        scale = height / 2  # Scaling factor based on desired height

        # For a regular tetrahedron, calculate positions of 4 vertices
        # Using standard coordinates for a regular tetrahedron
        # Vertices: (1,1,1), (1,-1,-1), (-1,1,-1), (-1,-1,1) scaled appropriately
        # Then translated to center of voxel space

        # Convert coordinates to voxel space and scale appropriately
        rel_x = x - center
        rel_y = y - center
        rel_z = z - center

        # Define the 4 faces of the tetrahedron using plane equations
        # Normalize scale for the tetrahedron dimensions
        normalized_scale = scale * 0.8  # Slightly adjusted for visual balance

        # A tetrahedron can be defined by 4 inequalities (each representing a face)
        # Face 1: x + y + z <= scale
        # Face 2: x - y - z <= scale
        # Face 3: -x + y - z <= scale
        # Face 4: -x - y + z <= scale

        face1 = (rel_x + rel_y + rel_z) <= normalized_scale
        face2 = (rel_x - rel_y - rel_z) <= normalized_scale
        face3 = (-rel_x + rel_y - rel_z) <= normalized_scale
        face4 = (-rel_x - rel_y + rel_z) <= normalized_scale

        # The tetrahedron is the intersection of these 4 half-spaces
        tetrahedron_mask = face1 & face2 & face3 & face4

        voxel[tetrahedron_mask] = 1
        return voxel
