from typing import Tuple, List, Optional
import numpy as np
from .base import PhantomGenerator


class Torus(PhantomGenerator):
    """
    A simple torus (donut).

    * Code generated by Grok.
    """

    def generate(
            self,
            size: int = 256,
            major_r: float = 0.28,
            minor_r: float = 0.10,
            thickness: Optional[float] = None,
    ):
        """ Generate a torus (donut).

        Args:
            size: the size of the voxel.
            major_r:
            minor_r:
            thickness:

        Returns:
            shape=(size, size, size), dtype=uint8, 0 or 1
        """
        voxel = self.get_blank_voxel(size)

        z, y, x = np.ogrid[:size, :size, :size]
        Z = (z - size / 2) / (size / 2)
        Y = (y - size / 2) / (size / 2)
        X = (x - size / 2) / (size / 2)

        rho = np.sqrt(X * X + Y * Y)

        dist_to_center_circle = np.abs(rho - major_r)

        torus_mask = dist_to_center_circle ** 2 + Z ** 2 <= minor_r ** 2

        if thickness is not None and 0 < thickness < minor_r:
            inner_mask = dist_to_center_circle ** 2 + Z ** 2 <= (minor_r - thickness) ** 2
            torus_mask = torus_mask & (~inner_mask)

        voxel[torus_mask] = 1
        return voxel